# Этапы
stages:
  - build
  - test
  - deploy

# workflow:
#   rules:
#     - if: $CI_COMMIT_BRANCH == 'main'
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
#     - if: $CI_COMMIT_BRANCH == 'developer'
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'developer'
#       when: always

# Сборка контейнеров
build-job:
  stage: build
  # Если работам с main или developer: то 
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
      when: always
      variables:
        DB_CONNECTION_STRING: $DB_CONNECTION
    - if: $CI_COMMIT_BRANCH == 'developer'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'developer'
      when: always
      variables:
        DB_CONNECTION_STRING: $DB_CONNECTION_TEST
    - when: manual
      variables:
        DB_CONNECTION_STRING: $DB_CONNECTION_TEST
  script:
      - cd server
      - docker build -t gardunov/backend:v1 --build-arg DB_CONNECTION=$DB_CONNECTION_STRING .
      - cd ../client
      - docker build -t gardunov/client:v1 .
      
      # Пушим контейнеры на dockerhub
      #- docker login -u gardunov -p $DOCKER_HUB_PASSWORD
      #- docker push gardunov/client:v1
      #- docker push gardunov/backend:v1


  tags:
    - build

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests."
    - sleep 3
    - echo "Unit tests complete."
  tags:
    - test
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
    - if: $CI_COMMIT_BRANCH == 'developer'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'developer'
      when: always
    - when: manual
  needs:
    - job: build-job

security-test-job:
  stage: test
  script:
    - echo "Running security tests."
    - sleep 3
    - echo "security tests complete."
  tags:
    - test
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
      when: always
    - when: manual
      allow_failure: true
  needs:
    - job: build-job
    
deploy-job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
    - if: $CI_COMMIT_BRANCH == 'developer'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'developer'
      when: always
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
      variables:
        RUN_PATH: '/'
    - variables:
        RUN_PATH: '/test'
  
  script:
    - cd ".$RUN_PATH"
    - docker compose up -d
    - docker compose logs
  tags:
    - deploy
  needs:
    - job: build-job
