stages:
  - build
  - test
  - deploy

#workflow:
  #rules:
    #- if: $CI_COMMIT_BRANCH == 'main'
      #when: always

variables:
  DEPLOY_ENV: "production"

build-job:
  stage: build
  script:
      #- docker login -u gardunov -p $DOCKER_HUB_PASSWORD
      - cd server
      - docker build -t gardunov/backend:v1 --build-arg DB_CONNECTION=$DB_CONNECTION .
      #- docker push gardunov/backend:v1
      - cd ../client
      - docker build -t gardunov/client:v1 .
      #- docker push gardunov/client:v1

  tags:
    - build

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests."
    - sleep 5
    - echo "Unit tests complete."
  tags:
    - test

deploy-job:
  stage: deploy
  script:
  #  - docker compose restart
    - docker compose up -d
    - docker compose logs
  tags:
    - deploy
